/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.test.factory.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CalcEntry service. Represents a row in the &quot;TestFactory_CalcEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.test.factory.model.impl.CalcEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.test.factory.model.impl.CalcEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CalcEntry
 * @generated
 */
@ProviderType
public interface CalcEntryModel
	extends AuditedModel, BaseModel<CalcEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a calc entry model instance should use the {@link CalcEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this calc entry.
	 *
	 * @return the primary key of this calc entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this calc entry.
	 *
	 * @param primaryKey the primary key of this calc entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the calc entry ID of this calc entry.
	 *
	 * @return the calc entry ID of this calc entry
	 */
	public long getCalcEntryId();

	/**
	 * Sets the calc entry ID of this calc entry.
	 *
	 * @param calcEntryId the calc entry ID of this calc entry
	 */
	public void setCalcEntryId(long calcEntryId);

	/**
	 * Returns the company ID of this calc entry.
	 *
	 * @return the company ID of this calc entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this calc entry.
	 *
	 * @param companyId the company ID of this calc entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this calc entry.
	 *
	 * @return the user ID of this calc entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this calc entry.
	 *
	 * @param userId the user ID of this calc entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this calc entry.
	 *
	 * @return the user uuid of this calc entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this calc entry.
	 *
	 * @param userUuid the user uuid of this calc entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this calc entry.
	 *
	 * @return the user name of this calc entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this calc entry.
	 *
	 * @param userName the user name of this calc entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this calc entry.
	 *
	 * @return the create date of this calc entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this calc entry.
	 *
	 * @param createDate the create date of this calc entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this calc entry.
	 *
	 * @return the modified date of this calc entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this calc entry.
	 *
	 * @param modifiedDate the modified date of this calc entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the num1 of this calc entry.
	 *
	 * @return the num1 of this calc entry
	 */
	public double getNum1();

	/**
	 * Sets the num1 of this calc entry.
	 *
	 * @param num1 the num1 of this calc entry
	 */
	public void setNum1(double num1);

	/**
	 * Returns the num2 of this calc entry.
	 *
	 * @return the num2 of this calc entry
	 */
	public double getNum2();

	/**
	 * Sets the num2 of this calc entry.
	 *
	 * @param num2 the num2 of this calc entry
	 */
	public void setNum2(double num2);

	/**
	 * Returns the operator of this calc entry.
	 *
	 * @return the operator of this calc entry
	 */
	@AutoEscape
	public String getOperator();

	/**
	 * Sets the operator of this calc entry.
	 *
	 * @param operator the operator of this calc entry
	 */
	public void setOperator(String operator);

	/**
	 * Returns the result of this calc entry.
	 *
	 * @return the result of this calc entry
	 */
	public double getResult();

	/**
	 * Sets the result of this calc entry.
	 *
	 * @param result the result of this calc entry
	 */
	public void setResult(double result);

	@Override
	public CalcEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}