import {ENTITY_TYPES, EntityType} from './constants';
import {EntityFormConfig, FieldDefinition} from '../types';

function createCountField(label: string): FieldDefinition {
	return {
		label,
		name: 'count',
		required: true,
		type: 'number',
		validators: [
			{message: 'please-enter-a-valid-number', type: 'digits'},
			{message: 'value-must-be-greater-than-0', type: 'min', value: 1},
		],
	};
}

function createBaseNameField(label: string): FieldDefinition {
	return {
		label,
		name: 'baseName',
		required: true,
		type: 'text',
	};
}

const ORGANIZATION_CONFIG: EntityFormConfig = {
	actionURL: '/ldf/org',
	entityType: ENTITY_TYPES.ORGANIZATION,
	fields: [
		createCountField('number-of-organizations'),
		createBaseNameField('base-organization-name'),
		{
			dataSource: '/ldf/data/organizations',
			defaultValue: '0',
			label: 'parent-organization',
			name: 'parentOrganizationId',
			required: false,
			type: 'select',
		},
		{
			defaultValue: false,
			label: 'create-organization-site',
			name: 'site',
			required: false,
			type: 'toggle',
		},
	],
	helpText: 'organization-help-text',
	icon: 'organizations',
	label: 'organizations',
};

const PAGES_CONFIG: EntityFormConfig = {
	actionURL: '/ldf/page',
	entityType: ENTITY_TYPES.PAGES,
	fields: [
		{
			label: 'number-of-pages',
			name: 'count',
			required: true,
			type: 'number',
			validators: [
				{message: 'please-enter-a-valid-number', type: 'digits'},
				{message: 'value-must-be-greater-than-0', type: 'min', value: 1},
			],
		},
		{
			label: 'base-page-name',
			name: 'baseName',
			required: true,
			type: 'text',
		},
		{
			dataSource: '/ldf/data/sites',
			label: 'site',
			name: 'groupId',
			required: true,
			type: 'select',
		},
		{
			defaultValue: 'portlet',
			label: 'page-type',
			name: 'type',
			options: [
				{label: 'page-type-portlet', value: 'portlet'},
				{label: 'page-type-content', value: 'content'},
				{label: 'page-type-node', value: 'node'},
				{label: 'page-type-embedded', value: 'embedded'},
				{label: 'page-type-link-to-layout', value: 'link_to_layout'},
				{label: 'page-type-url', value: 'url'},
				{label: 'page-type-panel', value: 'panel'},
				{label: 'page-type-full-page-application', value: 'full_page_application'},
			],
			required: true,
			type: 'select',
		},
		{
			advanced: true,
			defaultValue: false,
			label: 'private-page',
			name: 'privateLayout',
			required: false,
			type: 'toggle',
		},
		{
			advanced: true,
			defaultValue: false,
			label: 'hidden-page',
			name: 'hidden',
			required: false,
			type: 'toggle',
		},
	],
	helpText: 'pages-help-text',
	icon: 'page',
	label: 'pages',
};

const USER_CONFIG: EntityFormConfig = {
	actionURL: '/ldf/user',
	entityType: ENTITY_TYPES.USERS,
	fields: [
		createCountField('number-of-users'),
		createBaseNameField('base-user-name'),
		{
			advanced: true,
			defaultValue: 'liferay.com',
			group: 'identity',
			label: 'email-domain',
			name: 'emailDomain',
			required: false,
			type: 'text',
		},
		{
			advanced: true,
			defaultValue: 'test',
			group: 'identity',
			label: 'password',
			name: 'password',
			required: false,
			type: 'text',
		},
		{
			advanced: true,
			defaultValue: true,
			group: 'identity',
			label: 'male',
			name: 'male',
			required: false,
			type: 'toggle',
		},
		{
			advanced: true,
			defaultValue: '',
			group: 'identity',
			label: 'job-title',
			name: 'jobTitle',
			required: false,
			type: 'text',
		},
		{
			advanced: true,
			defaultValue: false,
			group: 'generator',
			label: 'faker-enable',
			name: 'fakerEnable',
			required: false,
			type: 'toggle',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/locales',
			defaultValue: 'en_US',
			group: 'generator',
			label: 'locale',
			name: 'locale',
			required: false,
			type: 'select',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/organizations',
			defaultValue: '',
			group: 'membership',
			label: 'organizations',
			name: 'organizationIds',
			required: false,
			type: 'multiselect',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/roles',
			defaultValue: '',
			group: 'membership',
			label: 'roles',
			name: 'roleIds',
			required: false,
			type: 'multiselect',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/user-groups',
			defaultValue: '',
			group: 'membership',
			label: 'user-groups',
			name: 'userGroupIds',
			required: false,
			type: 'multiselect',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/site-roles',
			defaultValue: '',
			group: 'membership',
			label: 'site-roles',
			name: 'siteRoleIds',
			required: false,
			type: 'multiselect',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/org-roles',
			defaultValue: '',
			group: 'membership',
			label: 'organization-roles',
			name: 'orgRoleIds',
			required: false,
			type: 'multiselect',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/sites',
			defaultValue: '',
			group: 'membership',
			label: 'sites',
			name: 'groupIds',
			required: false,
			type: 'multiselect',
		},
		{
			advanced: true,
			defaultValue: false,
			group: 'layout',
			label: 'generate-personal-site-layouts',
			name: 'generatePersonalSiteLayouts',
			required: false,
			type: 'toggle',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/layout-set-prototypes',
			defaultValue: '0',
			group: 'layout',
			label: 'public-layout-set-prototype',
			name: 'publicLayoutSetPrototypeId',
			required: false,
			type: 'select',
			visibleWhen: {field: 'generatePersonalSiteLayouts', value: 'true'},
		},
		{
			advanced: true,
			dataSource: '/ldf/data/layout-set-prototypes',
			defaultValue: '0',
			group: 'layout',
			label: 'private-layout-set-prototype',
			name: 'privateLayoutSetPrototypeId',
			required: false,
			type: 'select',
			visibleWhen: {field: 'generatePersonalSiteLayouts', value: 'true'},
		},
	],
	helpText: 'user-help-text',
	icon: 'user',
	label: 'users',
};

const ROLE_CONFIG: EntityFormConfig = {
	actionURL: '/ldf/role',
	entityType: ENTITY_TYPES.ROLES,
	fields: [
		createCountField('number-of-roles'),
		createBaseNameField('base-role-name'),
		{
			defaultValue: 'regular',
			label: 'role-type',
			name: 'roleType',
			options: [
				{label: 'regular', value: 'regular'},
				{label: 'site', value: 'site'},
				{label: 'organization', value: 'organization'},
				{label: 'asset-library', value: 'depot'},
				{label: 'account', value: 'account'},
				{label: 'publications', value: 'publications'},
				{label: 'provider', value: 'provider'},
			],
			required: true,
			type: 'select',
		},
		{
			advanced: true,
			defaultValue: '',
			label: 'description',
			name: 'description',
			required: false,
			type: 'textarea',
		},
	],
	helpText: 'role-help-text',
	icon: 'roles',
	label: 'roles',
};

const SITE_CONFIG: EntityFormConfig = {
	actionURL: '/ldf/site',
	entityType: ENTITY_TYPES.SITES,
	fields: [
		createCountField('number-of-sites'),
		createBaseNameField('base-site-name'),
		{
			defaultValue: 'open',
			label: 'membership-type',
			name: 'membershipType',
			options: [
				{label: 'open', value: 'open'},
				{label: 'restricted', value: 'restricted'},
				{label: 'private', value: 'private'},
			],
			required: true,
			type: 'select',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/sites',
			defaultValue: '0',
			group: 'layout',
			label: 'parent-site',
			name: 'parentGroupId',
			required: false,
			type: 'select',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/site-templates',
			defaultValue: '0',
			group: 'layout',
			label: 'site-template',
			name: 'siteTemplateId',
			required: false,
			type: 'select',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/layout-set-prototypes',
			defaultValue: '0',
			group: 'layout',
			label: 'public-layout-set-prototype',
			name: 'publicLayoutSetPrototypeId',
			required: false,
			type: 'select',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/layout-set-prototypes',
			defaultValue: '0',
			group: 'layout',
			label: 'private-layout-set-prototype',
			name: 'privateLayoutSetPrototypeId',
			required: false,
			type: 'select',
		},
		{
			advanced: true,
			defaultValue: true,
			group: 'content',
			label: 'manual-membership',
			name: 'manualMembership',
			required: false,
			type: 'toggle',
		},
		{
			advanced: true,
			defaultValue: false,
			group: 'content',
			label: 'inherit-content',
			name: 'inheritContent',
			required: false,
			type: 'toggle',
		},
		{
			advanced: true,
			defaultValue: true,
			group: 'content',
			label: 'active',
			name: 'active',
			required: false,
			type: 'toggle',
		},
		{
			advanced: true,
			defaultValue: '',
			group: 'content',
			label: 'description',
			name: 'description',
			required: false,
			type: 'textarea',
		},
	],
	helpText: 'site-help-text',
	icon: 'sites',
	label: 'sites',
};

const WCM_CONFIG: EntityFormConfig = {
	actionURL: '/ldf/wcm',
	entityType: ENTITY_TYPES.WCM,
	fields: [
		{
			label: 'number-of-articles',
			name: 'count',
			required: true,
			type: 'number',
			validators: [
				{message: 'please-enter-a-valid-number', type: 'digits'},
				{message: 'value-must-be-greater-than-0', type: 'min', value: 1},
			],
		},
		{
			label: 'base-article-title',
			name: 'baseName',
			required: true,
			type: 'text',
		},
		{
			dataSource: '/ldf/data/sites',
			label: 'sites',
			name: 'groupIds',
			required: true,
			type: 'multiselect',
		},
		{
			defaultValue: '0',
			label: 'content-type',
			name: 'createContentsType',
			options: [
				{label: 'simple-title-and-content', value: '0'},
				{label: 'dummy-random-content', value: '1'},
				{label: 'structure-and-template', value: '2'},
			],
			required: true,
			type: 'select',
		},
		{
			defaultValue: '',
			label: 'article-content',
			name: 'baseArticle',
			required: false,
			type: 'textarea',
			visibleWhen: {field: 'createContentsType', value: '0'},
		},
		{
			defaultValue: '5',
			label: 'title-words',
			name: 'titleWords',
			required: false,
			type: 'number',
			visibleWhen: {field: 'createContentsType', value: '1'},
		},
		{
			defaultValue: '3',
			label: 'total-paragraphs',
			name: 'totalParagraphs',
			required: false,
			type: 'number',
			visibleWhen: {field: 'createContentsType', value: '1'},
		},
		{
			defaultValue: '3',
			label: 'random-image-amount',
			name: 'randomAmount',
			required: false,
			type: 'number',
			visibleWhen: {field: 'createContentsType', value: '1'},
		},
		{
			defaultValue: '',
			label: 'image-link-urls',
			name: 'linkLists',
			required: false,
			type: 'textarea',
			visibleWhen: {field: 'createContentsType', value: '1'},
		},
		{
			dataSource: '/ldf/data/ddm-structures',
			defaultValue: '',
			label: 'ddm-structure',
			name: 'ddmStructureId',
			required: false,
			type: 'select',
			visibleWhen: {field: 'createContentsType', value: '2'},
		},
		{
			dataSource: '/ldf/data/ddm-templates',
			defaultValue: '',
			dependsOn: {field: 'ddmStructureId', paramName: 'structureId'},
			label: 'ddm-template',
			name: 'ddmTemplateId',
			required: false,
			type: 'select',
			visibleWhen: {field: 'createContentsType', value: '2'},
		},
		{
			advanced: true,
			defaultValue: '0',
			label: 'folder-id',
			name: 'folderId',
			required: false,
			type: 'text',
		},
		{
			advanced: true,
			dataSource: '/ldf/data/locales',
			defaultValue: '',
			label: 'locales',
			name: 'locales',
			required: false,
			type: 'multiselect',
		},
		{
			advanced: true,
			defaultValue: true,
			label: 'never-expire',
			name: 'neverExpire',
			required: false,
			type: 'toggle',
		},
		{
			advanced: true,
			defaultValue: true,
			label: 'never-review',
			name: 'neverReview',
			required: false,
			type: 'toggle',
		},
	],
	helpText: 'web-content-help-text',
	icon: 'web-content',
	label: 'web-content',
};

export const ENTITY_CONFIGS: Partial<Record<EntityType, EntityFormConfig>> = {
	[ENTITY_TYPES.ORGANIZATION]: ORGANIZATION_CONFIG,
	[ENTITY_TYPES.PAGES]: PAGES_CONFIG,
	[ENTITY_TYPES.ROLES]: ROLE_CONFIG,
	[ENTITY_TYPES.SITES]: SITE_CONFIG,
	[ENTITY_TYPES.USERS]: USER_CONFIG,
	[ENTITY_TYPES.WCM]: WCM_CONFIG,
};

export function getEntityConfig(entityType: EntityType): EntityFormConfig | undefined {
	return ENTITY_CONFIGS[entityType];
}
