terms.of.use.required=false
users.reminder.queries.enabled=false
passwords.default.policy.change.required=false
jsonws.web.service.api.discoverable=true
json.web.service.enabled=true
configuration.override.com.liferay.portal.security.configuration.BasicAuthHeaderSupportConfiguration_enabled=B"true"
auth.verifier.BasicAuthHeaderAuthVerifier.urls.includes=/api/*,/portal/api/*,/o/*,/xmlrpc/*
configuration.override.com.liferay.portal.security.auth.verifier.internal.basic.auth.header.configuration.BasicAuthHeaderAuthVerifierConfiguration~default_urlsIncludes="/api/*,/portal/api/*,/o/*,/xmlrpc*"
enterprise.product.notification.enabled=false
company.security.strangers=false
company.security.strangers.verify=false
company.security.update.password.required=false
admin.email.user.added.enabled=false
