/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.test.factory.model.impl;

import com.liferay.test.factory.model.CalcEntry;
import com.liferay.test.factory.service.CalcEntryLocalServiceUtil;

/**
 * The extended model base implementation for the CalcEntry service. Represents a row in the &quot;TestFactory_CalcEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CalcEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CalcEntryImpl
 * @see CalcEntry
 * @generated
 */
public abstract class CalcEntryBaseImpl
	extends CalcEntryModelImpl implements CalcEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a calc entry model instance should use the <code>CalcEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			CalcEntryLocalServiceUtil.addCalcEntry(this);
		}
		else {
			CalcEntryLocalServiceUtil.updateCalcEntry(this);
		}
	}

}