/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.test.factory.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.test.factory.model.CalcEntry;
import com.liferay.test.factory.model.CalcEntryModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CalcEntry service. Represents a row in the &quot;TestFactory_CalcEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CalcEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CalcEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CalcEntryImpl
 * @generated
 */
@JSON(strict = true)
public class CalcEntryModelImpl
	extends BaseModelImpl<CalcEntry> implements CalcEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a calc entry model instance should use the <code>CalcEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "TestFactory_CalcEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"calcEntryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"num1", Types.DOUBLE}, {"num2", Types.DOUBLE},
		{"operator", Types.VARCHAR}, {"result", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("calcEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("num1", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("num2", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("operator", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("result", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TestFactory_CalcEntry (calcEntryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,num1 DOUBLE,num2 DOUBLE,operator VARCHAR(75) null,result DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table TestFactory_CalcEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY calcEntry.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TestFactory_CalcEntry.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CalcEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _calcEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCalcEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _calcEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CalcEntry.class;
	}

	@Override
	public String getModelClassName() {
		return CalcEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CalcEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CalcEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CalcEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((CalcEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CalcEntry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CalcEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CalcEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CalcEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CalcEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<CalcEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<CalcEntry, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<CalcEntry, Object>>();

			attributeGetterFunctions.put(
				"calcEntryId", CalcEntry::getCalcEntryId);
			attributeGetterFunctions.put("companyId", CalcEntry::getCompanyId);
			attributeGetterFunctions.put("userId", CalcEntry::getUserId);
			attributeGetterFunctions.put("userName", CalcEntry::getUserName);
			attributeGetterFunctions.put(
				"createDate", CalcEntry::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CalcEntry::getModifiedDate);
			attributeGetterFunctions.put("num1", CalcEntry::getNum1);
			attributeGetterFunctions.put("num2", CalcEntry::getNum2);
			attributeGetterFunctions.put("operator", CalcEntry::getOperator);
			attributeGetterFunctions.put("result", CalcEntry::getResult);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<CalcEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CalcEntry, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CalcEntry, ?>>();

			attributeSetterBiConsumers.put(
				"calcEntryId",
				(BiConsumer<CalcEntry, Long>)CalcEntry::setCalcEntryId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CalcEntry, Long>)CalcEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<CalcEntry, Long>)CalcEntry::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CalcEntry, String>)CalcEntry::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CalcEntry, Date>)CalcEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CalcEntry, Date>)CalcEntry::setModifiedDate);
			attributeSetterBiConsumers.put(
				"num1", (BiConsumer<CalcEntry, Double>)CalcEntry::setNum1);
			attributeSetterBiConsumers.put(
				"num2", (BiConsumer<CalcEntry, Double>)CalcEntry::setNum2);
			attributeSetterBiConsumers.put(
				"operator",
				(BiConsumer<CalcEntry, String>)CalcEntry::setOperator);
			attributeSetterBiConsumers.put(
				"result", (BiConsumer<CalcEntry, Double>)CalcEntry::setResult);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getCalcEntryId() {
		return _calcEntryId;
	}

	@Override
	public void setCalcEntryId(long calcEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_calcEntryId = calcEntryId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public double getNum1() {
		return _num1;
	}

	@Override
	public void setNum1(double num1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_num1 = num1;
	}

	@JSON
	@Override
	public double getNum2() {
		return _num2;
	}

	@Override
	public void setNum2(double num2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_num2 = num2;
	}

	@JSON
	@Override
	public String getOperator() {
		if (_operator == null) {
			return "";
		}
		else {
			return _operator;
		}
	}

	@Override
	public void setOperator(String operator) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_operator = operator;
	}

	@JSON
	@Override
	public double getResult() {
		return _result;
	}

	@Override
	public void setResult(double result) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_result = result;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CalcEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CalcEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CalcEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CalcEntryImpl calcEntryImpl = new CalcEntryImpl();

		calcEntryImpl.setCalcEntryId(getCalcEntryId());
		calcEntryImpl.setCompanyId(getCompanyId());
		calcEntryImpl.setUserId(getUserId());
		calcEntryImpl.setUserName(getUserName());
		calcEntryImpl.setCreateDate(getCreateDate());
		calcEntryImpl.setModifiedDate(getModifiedDate());
		calcEntryImpl.setNum1(getNum1());
		calcEntryImpl.setNum2(getNum2());
		calcEntryImpl.setOperator(getOperator());
		calcEntryImpl.setResult(getResult());

		calcEntryImpl.resetOriginalValues();

		return calcEntryImpl;
	}

	@Override
	public CalcEntry cloneWithOriginalValues() {
		CalcEntryImpl calcEntryImpl = new CalcEntryImpl();

		calcEntryImpl.setCalcEntryId(
			this.<Long>getColumnOriginalValue("calcEntryId"));
		calcEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		calcEntryImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		calcEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		calcEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		calcEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		calcEntryImpl.setNum1(this.<Double>getColumnOriginalValue("num1"));
		calcEntryImpl.setNum2(this.<Double>getColumnOriginalValue("num2"));
		calcEntryImpl.setOperator(
			this.<String>getColumnOriginalValue("operator"));
		calcEntryImpl.setResult(this.<Double>getColumnOriginalValue("result"));

		return calcEntryImpl;
	}

	@Override
	public int compareTo(CalcEntry calcEntry) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), calcEntry.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CalcEntry)) {
			return false;
		}

		CalcEntry calcEntry = (CalcEntry)object;

		long primaryKey = calcEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CalcEntry> toCacheModel() {
		CalcEntryCacheModel calcEntryCacheModel = new CalcEntryCacheModel();

		calcEntryCacheModel.calcEntryId = getCalcEntryId();

		calcEntryCacheModel.companyId = getCompanyId();

		calcEntryCacheModel.userId = getUserId();

		calcEntryCacheModel.userName = getUserName();

		String userName = calcEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			calcEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			calcEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			calcEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			calcEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			calcEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		calcEntryCacheModel.num1 = getNum1();

		calcEntryCacheModel.num2 = getNum2();

		calcEntryCacheModel.operator = getOperator();

		String operator = calcEntryCacheModel.operator;

		if ((operator != null) && (operator.length() == 0)) {
			calcEntryCacheModel.operator = null;
		}

		calcEntryCacheModel.result = getResult();

		return calcEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CalcEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CalcEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CalcEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CalcEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CalcEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CalcEntry.class, ModelWrapper.class);

	}

	private long _calcEntryId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private double _num1;
	private double _num2;
	private String _operator;
	private double _result;

	public <T> T getColumnValue(String columnName) {
		Function<CalcEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CalcEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("calcEntryId", _calcEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("num1", _num1);
		_columnOriginalValues.put("num2", _num2);
		_columnOriginalValues.put("operator", _operator);
		_columnOriginalValues.put("result", _result);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("calcEntryId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("userId", 4L);

		columnBitmasks.put("userName", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("num1", 64L);

		columnBitmasks.put("num2", 128L);

		columnBitmasks.put("operator", 256L);

		columnBitmasks.put("result", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CalcEntry _escapedModel;

}